services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/9000' 2> /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress

  nginx:
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    image: ngnix
    container_name: nginx
    restart: always
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress

  static_site:
    build: ./requirements/bonus/static_site
    image: static_site
    container_name: static_site
    restart: always
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - inception

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception

networks:
  inception:
    driver: bridge
    name: inception


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/claghrab/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/claghrab/data/wordpress
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/claghrab/data/portainer
      o: bind